/*
1.사원테이블에서 부서 인원수가 6명이상인 부서코드 검색
*/
SELECT * FROM EMP;
SELECT DEPTNO ,COUNT(*)
FROM EMP 
GROUP BY DEPTNO
HAVING COUNT(*)>=6;

/*
2.사원테이블로부터 부서번호 ,업무별 급여합계를 계산하고자 한다 .다음과 같은 결과를 출력할수 있는
    SQL문장 작성 
    DEPTNO CLERK MANAGER PRESIDENT ANALYST SALSEMAN
    ------------------------------------------------
    10	    1300	2450	 5000	     0	       0
    20	    1900	2975    	0	  6000	       0
    30	    950	    2850     	0	     0	    5600
*/

SELECT DEPTNO,SUM(DECODE(JOB,'CLERK',SAL,0)),
        SUM(DECODE(JOB,'MANAGER',SAL,0)),
        SUM(DECODE(JOB,'PRESIDENT',SAL,0)),
        SUM(DECODE(JOB,'ANALYST',SAL,0)),
        SUM(DECODE(JOB,'SALESMAN',SAL,0))
FROM EMP
GROUP BY DEPTNO
ORDER BY 1;

/*
3. 사원테이블로 부터 년도별 ,월별 급여합계를 출력할 수 있는 SQL문장 작성?
*/
SELECT TO_CHAR(HIREDATE,'YYYY') 년,TO_CHAR(HIREDATE,'MM') 월,SUM(SAL) 급여
FROM EMP 
GROUP BY TO_CHAR(HIREDATE,'YYYY'),TO_CHAR(HIREDATE,'MM')
ORDER BY 1,2;


/*
4.사원테이블에서 부서별 COMM(커미션)을 포함하지 않는 연봉의합과  포함한 연봉의 합을 구하는 SQL을 작성하시오

*/
SELECT DEPTNO,SUM(NVL2(COMM,(SAL+COMM)*12,SAL*12) )

FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO
;
SELECT * FROM EMP;

SELECT DEPTNO,SUM(SAL*12) 

FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO
;
SELECT * FROM EMP;
/*
5.사원테이블에서 SALESMAN을 제외한 JOB별 급여합계
*/
SELECT JOB ,SUM(SAL)

FROM EMP 
GROUP BY JOB
HAVING JOB!='SALESMAN'
;
------------------------------------------------------------------------------------------------------------------

--1.
SELECT * FROM EMP;
SELECT * FROM DEPT;


SELECT EMPNO,ENAME,d.DEPTNO,DNAME FROM DEPT d,EMP e
WHERE d.DEPTNO=e.DEPTNO 
ORDER BY ENAME ASC;



--1-2 


SELECT EMPNO,ENAME,d.DEPTNO,DNAME 
FROM EMP e 
JOIN DEPT d ON e.DEPTNO=d.DEPTNO
ORDER BY ENAME ASC;



--1-3
SELECT EMPNO,ENAME,DEPTNO,DNAME FROM EMP NATURAL JOIN DEPT;




--2.
SELECT  EMPNO,ENAME,SAL,DNAME
FROM DEPT d,EMP e
WHERE d.DEPTNO=e.DEPTNO AND SAL>=2000 
ORDER BY SAL ASC;

--2-1

SELECT  EMPNO,ENAME,SAL,DNAME FROM EMP JOIN DEPT USING (DEPTNO)
WHERE SAL>=2000
ORDER BY SAL ASC;



--2-2
SELECT*FROM EMP;
SELECT EMPNO,ENAME,SAL,DNAME 
FROM EMP e JOIN DEPT d ON 
e.DEPTNO=d.DEPTNO AND SAL>=2000
ORDER BY SAL DESC;


--3
SELECT EMPNO,ENAME,JOB,SAL,DNAME

FROM EMP e,DEPT d 

WHERE e.DEPTNO=d.DEPTNO AND JOB='MANAGER' AND SAL>=2500
ORDER BY EMPNO ASC ;
--3-2
SELECT EMPNO,ENAME,JOB,SAL,DNAME
FROM EMP e JOIN DEPT d ON
e.DEPTNO=d.DEPTNO AND JOB='MANAGER' AND SAL>=2500
ORDER BY EMPNO ASC;
--4
SELECT * FROM SALGRADE;

SELECT EMPNO,ENAME,SAL,GRADE

FROM EMP e ,SALGRADE s

WHERE SAL<=HISAL AND SAL>=LOSAL AND GRADE=4 
ORDER BY SAL DESC;
--4-2
SELECT EMPNO,ENAME,SAL,GRADE 
FROM EMP JOIN SALGRADE ON
SAL<=HISAL AND SAL>=LOSAL AND GRADE=4
ORDER BY SAL DESC;



--5 

SELECT EMPNO ,ENAME,DNAME,SAL,GRADE 

FROM EMP e,DEPT d,SALGRADE 

WHERE e.DEPTNO=d.DEPTNO AND SAL>=LOSAL AND SAL<=HISAL 

ORDER BY GRADE DESC;


--5.1 
SELECT EMPNO ,ENAME ,DNAME ,SAL,GRADE FROM EMP NATURAL JOIN DEPT 
JOIN SALGRADE ON SAL>=LOSAL AND SAL<=HISAL
ORDER BY GRADE DESC;


--5-2
SELECT EMPNO,ENAME,DNAME,SAL,GRADE 
FROM EMP e JOIN DEPT d ON 
e.DEPTNO=d.DEPTNO 
JOIN SALGRADE ON 
SAL>=LOSAL AND SAL<=HISAL
ORDER BY GRADE DESC;




--6 
SELECT e.ENAME ,m.ENAME

FROM EMP e ,EMP m

WHERE e.MGR=m.EMPNO ;

SELECT * FROM EMP;
--6-2

SELECT e.ENAME,m.ENAME 
FROM EMP e JOIN EMP m 
ON e.MGR=m.EMPNO;



--7
SELECT e.ENAME,m.ENAME,k.ENAME

FROM EMP e ,EMP m,EMP K

WHERE e.MGR=m.EMPNO AND m.MGR=K.EMPNO;

--7-2
SELECT e.ENAME,m.ENAME,k.ENAME
FROM EMP e JOIN EMP m ON
e.MGR=m.EMPNO 
JOIN EMP k 
ON m.MGR=k.EMPNO;



--8
SELECT e.ENAME,m.ENAME,k.ENAME

FROM EMP e ,EMP m,EMP K

WHERE e.MGR=m.EMPNO(+) AND m.MGR=K.EMPNO(+);

--8-2
SELECT e.ENAME,m.ENAME,k.ENAME
FROM EMP e LEFT OUTER JOIN EMP m ON
e.MGR=m.EMPNO 
LEFT OUTER JOIN EMP k 
ON m.MGR=k.EMPNO;


SELECT *FROM EMP;