--1)
SELECT e.DEPTNO 부서코드, COUNT(*) 인원수
FROM EMP e
GROUP BY DEPTNO
HAVING COUNT(*)>=6;

--2)
SELECT  DEPTNO, 
        SUM(decode(job,'CLERK',sal)) "CLERK",
        SUM(DECODE(JOB, 'MANAGER', SAL)) "MANAGER",
        SUM(DECODE(JOB, 'PRESIDENT',SAL)) "PRESIDENT",
        SUM(DECODE(JOB, 'ANALYST',SAL)) "ANALYST",
        SUM(DECODE(JOB, 'SALESMAN',SAL)) "SALESMAN"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--3)
SELECT TO_CHAR(HIREDATE,'YYYY') "년",TO_CHAR(HIREDATE,'MM') "월",SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),TO_CHAR(HIREDATE,'MM')
ORDER BY TO_CHAR(HIREDATE,'YYYY') ASC;

--4) 
SELECT DEPTNO, SUM(SAL*12) "연봉"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT DEPTNO, SUM(NVL2(COMM,(COMM+SAL)*12,SAL*12)) "연봉"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--5(
SELECT JOB, SUM(SAL)
FROM EMP
WHERE JOB <> 'ANALYST'
GROUP BY JOB;





