--1)
SELECT NAME, TO_CHAR(BIRTHDAY, 'MMDD') "Birthday" FROM STUDENT;
SELECT NAME, CONCAT(CONCAT(CONCAT(TO_CHAR(BIRTHDAY,'MM'),'월 '),
                    TO_CHAR(BIRTHDAY,'DD')),'일') FROM STUDENT;
                    
                    
--2)
SELECT NAME,TEL,SUBSTR(TEL,1,INSTR(TEL,')')-1) "AREA CODE"
FROM STUDENT
WHERE DEPTNO1 = '201';

--3)
SELECT NAME, JUMIN, REPLACE(JUMIN,SUBSTR(JUMIN,7),'*******') "REPLACE" 
FROM STUDENT
WHERE DEPTNO1 = '101';

SELECT NAME, JUMIN, REPLACE(JUMIN,SUBSTR(JUMIN,7),'-*******') "REPLACE" 
FROM STUDENT
WHERE DEPTNO1 = '101';
INSTR
--4)
SELECT NAME, TEL, REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,'-')),'-****')
FROM STUDENT
WHERE DEPTNO1 = '101';