--07.그룹함수 실습문제
--1.사원테이블에서 부서별 인원수가 6명 이상인 부서
SELECT DEPTNO,COUNT(*) "6명이상인 부서"
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 6;

--2.사원테이블로부터 부서번호,  업무별 급여합계를 계산하고자 한다.
SELECT DEPTNO, SUM(DECODE(JOB,'CLERK',SAL))CLERK,
                SUM(DECODE(JOB,'MANAGER',SAL))MANAGER,
                SUM(DECODE(JOB,'PRESIDENT',SAL))PRESIDENT,
                SUM(DECODE(JOB,'ANALYST',SAL))ANALYST,
                SUM(DECODE(JOB,'SALESMAN',SAL))SALESMAN
FROM EMP
GROUP  BY DEPTNO
ORDER BY DEPTNO;

--3.사원테이블로부터 년도별,월별 급여합계를 출력
SELECT TO_CHAR(HIREDATE,'YYYY')"년", 
        TO_CHAR(HIREDATE,'MM')"월",
        SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'),
        TO_CHAR(HIREDATE,'MM')
ORDER BY 년,월;

--4.사원테이블에서 부서별 COMM(커미션)을 포함하지 않은 연봉의 합과 포함한 연봉의 합을  구하는
SELECT DEPTNO, SUM(SAL*12)연봉
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT DEPTNO, SUM(SAL*12+NVL(COMM,0)) 연봉
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--5.사원테이블에서 SALESMAN을 제외한 JOB별 급여합계
SELECT JOB, SUM(SAL)
FROM EMP
WHERE JOB <>'SALESMAN'
GROUP BY JOB;

