--이력테이블 삭제
DROP TABLE HMGDETAIL;
DROP TABLE HMLOGIN;
DROP TABLE HMDETAIL;
DROP TABLE HCATE;
DROP TABLE HORDER;

--나머지 테이블 삭제
DROP TABLE MDETAIL;
DROP TABLE BKDETAIL;
DROP TABLE RCV;
DROP TABLE ORDETAIL;
DROP TABLE CART;
DROP TABLE BORDER;
DROP TABLE BOOK;
DROP TABLE CATE;
DROP TABLE MLOGIN;
DROP TABLE MGDETAIL;

--시퀀스 삭제
DROP SEQUENCE MGNO_SEQ;
DROP SEQUENCE MNO_SEQ;
DROP SEQUENCE CGNO_SEQ;
DROP SEQUENCE BNO_SEQ;
DROP SEQUENCE BIFNO_SEQ;
DROP SEQUENCE RNO_SEQ;
DROP SEQUENCE ONO_SEQ;
DROP SEQUENCE DNO_SEQ;
DROP SEQUENCE CNO_SEQ;

--시퀀스 생성
CREATE SEQUENCE MGNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE MNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CGNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BIFNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE RNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE ONO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE DNO_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE CNO_SEQ INCREMENT BY 1 START WITH 1;
------------------------------------------------------------------------

--회원등급상세 테이블
CREATE TABLE MGDETAIL(
MGNO NUMBER(2) CONSTRAINT MGDETAIL_MGNO_PK PRIMARY KEY, 
MGRADE VARCHAR2(15) CONSTRAINT MGDETAIL_MDRADE_NN NOT NULL, 
MGRATE NUMBER(2,2) CONSTRAINT MGDETAIL_MGRATE_NN NOT NULL, 
CONSTRAINT MGDETAIL_MGRADE_UK UNIQUE(MGRADE));

--회원로그인 테이블
CREATE TABLE MLOGIN(
MNO NUMBER(10) CONSTRAINT MLOGIN_MNO_PK PRIMARY KEY, 
MID VARCHAR2(20) CONSTRAINT MLOGIN_MID_NN NOT NULL, 
MPASS VARCHAR2(20) CONSTRAINT LOGIN_MPASS_NN NOT NULL, 
MGNO NUMBER(2) DEFAULT 1 CONSTRAINT LOGIN_MGNO_NN NOT NULL, 
CONSTRAINT MLOGIN_MID_UK UNIQUE(MID), 
CONSTRAINT MLOGIN_MGNO_FK FOREIGN KEY(MGNO) REFERENCES MGDETAIL(MGNO));

--회원상세 테이블
CREATE TABLE MDETAIL(
MNO NUMBER(10) CONSTRAINT MDETAIL_MNO_PK PRIMARY KEY, 
MNAME VARCHAR2(18) CONSTRAINT MDETAIL_MNAME_NN NOT NULL, 
MADDR VARCHAR2(150), 
MPHONE VARCHAR2(11), 
MPOINT NUMBER(10) DEFAULT 1000 CONSTRAINT MDETAIL_MPOINT_NN NOT NULL, 
MEMAIL VARCHAR2(30) CONSTRAINT MDETAIL_MEMAIL_NN NOT NULL, 
MDATE DATE DEFAULT SYSDATE CONSTRAINT MDETAIL_MDATE_NN NOT NULL, 
CONSTRAINT MDETAIL_MNO_FK FOREIGN KEY (MNO) REFERENCES MLOGIN(MNO) ON DELETE CASCADE);
                        
--도서카테고리 테이블
CREATE TABLE CATE(
CGNO NUMBER(2) CONSTRAINT CATE_CGNO_PK PRIMARY KEY, 
CGNAME VARCHAR2(30) CONSTRAINT CATE_CGNAME_NN NOT NULL,
UPCGNO NUMBER(2) CONSTRAINT CATE_UPCGNO_FK REFERENCES CATE(CGNO));

--도서 테이블
CREATE TABLE BOOK(
BNO NUMBER(10) CONSTRAINT BOOK_BNO_PK PRIMARY KEY, 
BNAME VARCHAR2(100) CONSTRAINT BOOK_BNAME_NN NOT NULL, 
CGNO NUMBER(2) DEFAULT 99 CONSTRAINT BOOK_CGNO_NN NOT NULL, 
BCPRICE NUMBER(10) CONSTRAINT BOOK_BCPRICE_NN NOT NULL, 
BDISRATE NUMBER(2,2) CONSTRAINT BOOK_BDISRATE_NN NOT NULL, 
BPRICE NUMBER(10) CONSTRAINT BOOK_BPRICE_NN NOT NULL, 
BSTOCK NUMBER(6) CONSTRAINT BOOK_BSTOCK_NN NOT NULL, 
BAUTH VARCHAR2(50) CONSTRAINT BOOK_BAUTH_NN NOT NULL, 
BPUBLISHER VARCHAR2(30) CONSTRAINT BOOK_BPUBLISHER_NN NOT NULL, 
BPUBDATE DATE CONSTRAINT BOOK_BPUBDATE_NN NOT NULL, 
BIMAGE VARCHAR2(30) DEFAULT 'none.jpg' CONSTRAINT BOOK_BIMAGE_NN NOT NULL, 
CONSTRAINT BOOK_CGNO_FK FOREIGN KEY(CGNO) REFERENCES CATE(CGNO));

--도서상세 테이블
CREATE TABLE BKDETAIL(
BIFNO NUMBER(10) CONSTRAINT BKDETAIL_BIFNO_PK PRIMARY KEY, 
BNO NUMBER(10) CONSTRAINT BKDETAIL_BNO_NN NOT NULL, 
BINFO VARCHAR2(4000) CONSTRAINT BKDETAIL_BINFO_NN NOT NULL, 
CONSTRAINT BKDETAIL_BNO_FK FOREIGN KEY(BNO) REFERENCES BOOK(BNO));                     

--입고 테이블
CREATE TABLE RCV(
RNO NUMBER(10) CONSTRAINT RCV_RNO_PK PRIMARY KEY, 
BNO NUMBER(10) CONSTRAINT RCV_BNO_NN NOT NULL, 
RSTOCK NUMBER(6) CONSTRAINT RCV_RSTOCK_NN NOT NULL, 
RBSTOCK NUMBER(6) CONSTRAINT RCV_RBSTOCK_NN NOT NULL, 
RDATE DATE DEFAULT SYSDATE CONSTRAINT RCV_RDATE_NN NOT NULL, 
CONSTRAINT RCV_BNO_FK FOREIGN KEY(BNO) REFERENCES BOOK(BNO));

--주문 테이블
CREATE TABLE BORDER(
ONO NUMBER(10) CONSTRAINT BORDER_ONO_PK PRIMARY KEY, 
MNO NUMBER(10) CONSTRAINT BORDER_MNO_NN NOT NULL, 
TPRICE NUMBER(10) CONSTRAINT BORDER_TRPICE_NN NOT NULL, 
ODATE DATE DEFAULT SYSDATE CONSTRAINT BORDER_ODATE_NN NOT NULL, 
OADDR VARCHAR2(150) CONSTRAINT BORDER_OADDR_NN NOT NULL, 
STATUS VARCHAR2(12) CONSTRAINT BORDER_STATUS_NN NOT NULL, 
PMETHOD VARCHAR2(15) CONSTRAINT BORDER_PMETHOD_NN NOT NULL, 
PAID NUMBER(1) CONSTRAINT BORDER_PAID_NN NOT NULL, 
ANAME VARCHAR2(18) CONSTRAINT BORDER_ANAME_NN NOT NULL, 
APHONE VARCHAR2(11) CONSTRAINT BORDER_APHONE_NN NOT NULL, 
ODETAIL VARCHAR2(100) CONSTRAINT BORDER_ODETAIL_NN NOT NULL, 
ORQUEST VARCHAR2(150) CONSTRAINT BORDER_ORQUEST_NN NOT NULL, 
CONSTRAINT BORDER_MNO_FK FOREIGN KEY(MNO) REFERENCES MLOGIN(MNO) ON DELETE CASCADE, 
CONSTRAINT BORDER_STATUS_CK CHECK (STATUS IN('결제대기','결제완료','배송대기','배송중','배송완료','주문취소')), 
CONSTRAINT BORDER_PMETHOD_CK CHECK (PMETHOD IN('카드_삼송','무통장입금','휴대폰결제','카드_궁민')), 
CONSTRAINT BORDER_PAID_CK CHECK (PAID IN(0,1)));

--주문상세 테이블
CREATE TABLE ORDETAIL(
DNO NUMBER(10) CONSTRAINT ORDETAIL_DNO_PK PRIMARY KEY, 
ONO NUMBER(10) CONSTRAINT ORDETAIL_ONO_NN NOT NULL, 
BNO NUMBER(10) CONSTRAINT ORDETAIL_BNO_NN NOT NULL, 
BCOUNT NUMBER(3) CONSTRAINT ORDETAIL_BCOUNT_NN NOT NULL, 
PRICE NUMBER(10) CONSTRAINT ORDETAIL_PRICE_NN NOT NULL, 
CONSTRAINT ORDETAIL_ONO_FK FOREIGN KEY(ONO) REFERENCES BORDER(ONO) ON DELETE CASCADE, 
CONSTRAINT ORDETAIL_BNO_FK FOREIGN KEY(BNO) REFERENCES BOOK(BNO), 
CONSTRAINT ORDETAIL_BCOUNT_CK CHECK (BCOUNT > 0));

--장바구니 테이블
CREATE TABLE CART(
CNO NUMBER(10) CONSTRAINT CART_CNO_PK PRIMARY KEY, 
MNO NUMBER(10) CONSTRAINT CART_MNO_NN NOT NULL, 
BNO NUMBER(10) CONSTRAINT CART_BNO_NN NOT NULL, 
BCOUNT NUMBER(3) CONSTRAINT CART_BCOUNT_NN NOT NULL, 
CONSTRAINT CART_MNO_FK FOREIGN KEY(MNO) REFERENCES MLOGIN(MNO) ON DELETE CASCADE, 
CONSTRAINT CART_BNO_FK FOREIGN KEY(BNO) REFERENCES BOOK(BNO), 
CONSTRAINT CART_BCOUNT_CK CHECK (BCOUNT > 0));    

--회원등급이력 테이블
CREATE TABLE HMGDETAIL(
MGNO NUMBER(2)CONSTRAINT HMGDETAIL_MGNO_NN NOT NULL, 
MGRADE VARCHAR2(15) CONSTRAINT HMGDETAIL_MGRADE_NN NOT NULL, 
MGRATE NUMBER(2,2) CONSTRAINT HMGDETAIL_MGRATE_NN NOT NULL, 
CNDATE DATE DEFAULT SYSDATE, 
CONSTRAINT HMGDETAIL_MGNO_FK FOREIGN KEY(MGNO) REFERENCES MGDETAIL(MGNO));

--회원로그인이력 테이블
CREATE TABLE HMLOGIN(
MNO NUMBER(10) CONSTRAINT HMLOGIN_MNO_NN NOT NULL, 
MID VARCHAR2(20) CONSTRAINT HMLOGIN_MID_NN NOT NULL, 
MPASS VARCHAR2(20) CONSTRAINT HMLOGIN_MPASS_NN NOT NULL, 
MGNO NUMBER(2) CONSTRAINT HMLOGIN_MGNO_NN NOT NULL, 
CNDATE DATE DEFAULT SYSDATE, 
CONSTRAINT HMLOGIN_MNO_FK FOREIGN KEY(MNO) REFERENCES MLOGIN(MNO) ON DELETE CASCADE, 
CONSTRAINT HMLOGIN_MGNO_FK FOREIGN KEY(MGNO) REFERENCES MGDETAIL(MGNO));

--회원상세이력 테이블
CREATE TABLE HMDETAIL(
MNO NUMBER(10) CONSTRAINT HMDETAIL_MNO_FK REFERENCES MDETAIL(MNO) ON DELETE CASCADE, 
MNAME VARCHAR2(18), 
MADDR VARCHAR2(150), 
MPHONE VARCHAR2(11) CONSTRAINT HMDETAIL_MPHONE_NN NOT NULL, 
MPOINT NUMBER(10) CONSTRAINT HMDETAIL_MPOINT_NN NOT NULL, 
MEMAIL VARCHAR2(30) CONSTRAINT HMDETAIL_MEMAIL_NN NOT NULL, 
CNDATE DATE DEFAULT SYSDATE);

--도서카테고리이력 테이블
CREATE TABLE HCATE(
CGNO NUMBER(2) CONSTRAINT HCATE_CGNO_NN NOT NULL, 
CGNAME VARCHAR2(30) CONSTRAINT HCATE_CGMAME_NN NOT NULL, 
UPCGNO NUMBER(2), 
CNDATE DATE DEFAULT SYSDATE, 
CONSTRAINT HACATE_CGNO_FK FOREIGN KEY(CGNO) REFERENCES CATE(CGNO), 
CONSTRAINT HACATE_UPCGNO_FK FOREIGN KEY(UPCGNO) REFERENCES CATE(CGNO));

--주문이력 테이블
CREATE TABLE HORDER(
ONO NUMBER(10), 
MNO NUMBER(10) CONSTRAINT HORDER_MNO_NN NOT NULL, 
TPRICE NUMBER(10) CONSTRAINT HORDER_TPRICE_NN NOT NULL, 
ODATE DATE CONSTRAINT HORDER_ODATE_NN NOT NULL, 
OADRR VARCHAR2(150) CONSTRAINT HORDER_OADRR_NN NOT NULL, 
STATUS VARCHAR2(12) CONSTRAINT HORDER_STATUS_NN NOT NULL, 
PMETHOD VARCHAR2(15) CONSTRAINT HORDER_PMETHOD_NN NOT NULL, 
PAID NUMBER(1) CONSTRAINT HORDER_PAID_NN NOT NULL, 
ANAME VARCHAR2(18) CONSTRAINT HORDER_ANAME_NN NOT NULL, 
APHONE VARCHAR2(11) CONSTRAINT HORDER_APHONE_NN NOT NULL, 
ODETAIL VARCHAR2(100) CONSTRAINT HORDER_ODETAIL_NN NOT NULL, 
ORQUEST VARCHAR2(150) CONSTRAINT HORDER_ORQUEST_NN NOT NULL, 
CNDATE DATE DEFAULT SYSDATE, 
CONSTRAINT HORDER_ONO_FK FOREIGN KEY(ONO) REFERENCES BORDER(ONO) ON DELETE CASCADE, 
CONSTRAINT HORDER_MNO_FK FOREIGN KEY(MNO) REFERENCES MLOGIN(MNO), 
CONSTRAINT HORDER_STATUS_CK CHECK (STATUS IN('결제대기','결제완료','배송대기','배송중','배송완료','주문취소')), 
CONSTRAINT HORDER_PMETHOD_CK CHECK (PMETHOD IN('카드_삼송','무통장입금','휴대폰결제','카드_궁민')), 
CONSTRAINT HORDER_PAID_CK CHECK (PAID BETWEEN 0 AND 1));

--카테고리번호 삭제시 도서 카테고리번호 0으로 초기화하는 트리거
--DROP TRIGGER BOOK_CGNO_DELETE;
CREATE OR REPLACE TRIGGER BOOK_CGNO_DELETE
 BEFORE DELETE ON CATE FOR EACH ROW
BEGIN
    UPDATE BOOK
       SET CGNO = 99
     WHERE CGNO = :OLD.CGNO;
END;
/