SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'BLAKE'); 

SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER');

SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP);

SELECT EMPNO, ENAME, SAL FROM EMP WHERE
DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'CLARK') AND
SAL > (SELECT SAL FROM EMP WHERE EMPNO = '7698');

SELECT EMPNO, ENAME, DEPTNO, SAL FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO) ORDER BY DEPTNO;