SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROFESSOR;
SELECT * FROM STUDENT JOIN DEPARTMENT ON DEPTNO1 = DEPTNO OR DEPTNO2 = DEPTNO ORDER BY NAME;

--1
SELECT DNAME, MAX(HEIGHT) MAX_HEIGHT, MAX(WEIGHT) MAX_WEIGHT FROM (SELECT * FROM STUDENT JOIN DEPARTMENT ON DEPTNO1 = DEPTNO OR DEPTNO2 = DEPTNO) GROUP BY DNAME ORDER BY DNAME;

--2
SELECT S2.DNAME, S2.HEIGHT MAX_HEIGHT, S2.NAME, S2.HEIGHT
FROM (SELECT DNAME, MAX(HEIGHT) MAX_HEIGHT FROM (SELECT * FROM STUDENT JOIN DEPARTMENT ON DEPTNO1 = DEPTNO OR DEPTNO2 = DEPTNO) GROUP BY DNAME) S1
JOIN (SELECT * FROM STUDENT JOIN DEPARTMENT ON DEPTNO1 = DEPTNO OR DEPTNO2 = DEPTNO) S2 ON S1.MAX_HEIGHT = S2.HEIGHT AND S1.DNAME = S2.DNAME ORDER BY DNAME;

--3
SELECT S2.GRADE, S2.NAME, S2.HEIGHT, S1.AVG_HEIGHT AVG_HEIGHT
FROM (SELECT GRADE, ROUND(AVG(HEIGHT), 1) AVG_HEIGHT FROM STUDENT GROUP BY GRADE) S1
JOIN STUDENT S2 ON S2.HEIGHT > S1.AVG_HEIGHT AND S1.GRADE = S2.GRADE ORDER BY GRADE;

--4
SELECT NAME, PAY FROM PROFESSOR ORDER BY PAY DESC;

SELECT ROWNUM, P.NAME, P.PAY FROM (SELECT NAME, PAY FROM PROFESSOR ORDER BY PAY DESC) P WHERE ROWNUM <=5;

SELECT * FROM (SELECT ROWNUM PAY_RANK, NAME, PAY FROM (SELECT NAME, PAY FROM PROFESSOR ORDER BY PAY DESC)) P
WHERE P.PAY_RANK >= 3 and P.PAY_RANK <= 5;