SELECT * FROM STUDENT;

SELECT NAME, SUBSTR(JUMIN, 3, 4) Birthday FROM STUDENT WHERE DEPTNO1 = '101';
SELECT NAME, SUBSTR(JUMIN, 3, 2)||'월 '||SUBSTR(JUMIN, 5, 2)||'일' Birthday FROM STUDENT WHERE DEPTNO1 = '101';

SELECT NAME, TEL, SUBSTR(TEL, 1, INSTR(TEL, ')')-1) "AREA CODE" FROM STUDENT WHERE DEPTNO1 = '201';

SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN, 7), '*******') REPLACE FROM STUDENT WHERE DEPTNO1 = '101';
SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN, 7), '-*******') REPLACE FROM STUDENT WHERE DEPTNO1 = '101';

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, '-')+1), '****') REPLACE FROM STUDENT WHERE DEPTNO1 = '101';