--ORACLE JOIN
SELECT EMPNO, ENAME, EMP.DEPTNO, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY ENAME;

SELECT EMPNO, ENAME, SAL, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL >= 2000
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, JOB, SAL, DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND JOB = 'MANAGER' AND SAL >= 2500
ORDER BY EMPNO;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE G
WHERE (E.SAL >= G.LOSAL AND E.SAL <= G.HISAL) AND GRADE = '4'
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, DNAME, SAL, GRADE
FROM EMP E, DEPT D, SALGRADE G
WHERE E.DEPTNO = D.DEPTNO AND (E.SAL >= G.LOSAL AND E.SAL <= G.HISAL)
ORDER BY GRADE DESC;

SELECT E.ENAME, M.ENAME 
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO;

SELECT E.ENAME, M.ENAME, P.ENAME 
FROM EMP E, EMP M, EMP P
WHERE E.MGR = M.EMPNO AND M.MGR = P.EMPNO;

SELECT E.ENAME, M.ENAME, P.ENAME 
FROM EMP E, EMP M, EMP P
WHERE E.MGR = M.EMPNO(+) AND M.MGR = P.EMPNO(+);

--ANSI JOIN
SELECT EMPNO, ENAME, DEPTNO, DNAME
FROM EMP NATURAL JOIN DEPT;

SELECT EMPNO, ENAME, SAL, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO AND SAL >= 2000
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, JOB, SAL, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO AND JOB = 'MANAGER' AND SAL >= 2500
ORDER BY EMPNO;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E JOIN SALGRADE G ON (E.SAL >= G.LOSAL AND E.SAL <= G.HISAL) AND GRADE = '4'
ORDER BY SAL DESC;

SELECT EMPNO, ENAME, DNAME, SAL, GRADE
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE G ON E.SAL >= G.LOSAL AND E.SAL <= G.HISAL
ORDER BY GRADE DESC;

SELECT E.ENAME, M.ENAME 
FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO;

SELECT E.ENAME, M.ENAME, P.ENAME 
FROM EMP E JOIN EMP M ON E.MGR = M.EMPNO
JOIN EMP P ON M.MGR = P.EMPNO;

SELECT E.ENAME, M.ENAME, P.ENAME 
FROM EMP E LEFT OUTER JOIN EMP M ON E.MGR = M.EMPNO
LEFT OUTER JOIN EMP P ON M.MGR = P.EMPNO;