SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) >= 6;

SELECT DEPTNO, SUM(DECODE(JOB, 'CLERK', SAL, 0)) CLERK, SUM(DECODE(JOB, 'MANAGER', SAL, 0)) MANAGER,
               SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) PRESIDENT, SUM(DECODE(JOB, 'ANALYST', SAL, 0)) ANALYST,
               SUM(DECODE(JOB, 'SALESMAN', SAL, 0)) SALESMAN
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT TO_CHAR(HIREDATE, 'YYYY') 년, TO_CHAR(HIREDATE, 'MM') 월, SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), TO_CHAR(HIREDATE, 'MM')
ORDER BY 1, 2;

SELECT DEPTNO, SUM(SAL) 연봉
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;
SELECT DEPTNO, SUM(SAL) + SUM(DECODE(COMM, NULL, 0, COMM)) 연봉
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB
HAVING JOB != 'SALESMAN';