1. 부서테이블과 사원테이블에서 사번, 사원명, 부서코드, 부서명을 검색하시오.
  사원명 오름차순 정렬할 것.
--ORACLE JOIN
SELECT EMPNO 사번,ENAME 사원명,E.DEPTNO 부서코드,DNAME 부서명
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO
ORDER BY 사원명;
--ANSI JOIN
SELECT EMPNO 사번,ENAME 사원명,E.DEPTNO 부서코드,DNAME 부서명
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
ORDER BY 사원명;

2. 부서테이블과 사원테이블에서 사번, 사원명, 급여, 부서명을 검색하시오.
  단, 급여가 2000 이상인 사원에 대하여 급여기준으로 내림차순 정렬할 것.
--ORACLE JOIN
SELECT EMPNO 사번, ENAME 사원명, SAL 급여, DNAME 부서명
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND SAL>=2000
ORDER BY SAL DESC;
--ANSI JOIN
SELECT EMPNO 사번, ENAME 사원명, SAL 급여, DNAME 부서명
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO AND SAL>=2000
ORDER BY SAL DESC;

3. 부서테이블과 사원테이블에서 사번, 사원명, 업무, 급여, 부서명을 검색하시오.
  단, 업무가 MANAGER이며 급여가 2500 이상인 사원에 대하여 사번을 기준으로 오름차순 정렬할 것.
--ORACLE JOIN
SELECT EMPNO 사번, ENAME 사원명, JOB 업무, SAL 급여, DNAME 부서명
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND JOB='MANAGER' AND SAL >= 2500
ORDER BY EMPNO;
--ANSI JOIN
SELECT EMPNO 사번, ENAME 사원명, JOB 업무, SAL 급여, DNAME 부서명
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO AND JOB='MANAGER' AND SAL >= 2500
ORDER BY EMPNO;

4. 사원테이블과 급여등급테이블에서 사번, 사원명, 급여, 등급을 검색하시오.
  단, 등급은 급여가 하한값과 상한값 범위에 포함되고 등급이 4이며 급여를 기준으로 내림차순 정렬할 것.
--OREACLE JOIN
SELECT EMPNO 사번, ENAME 사원명, SAL 급여, GRADE 등급
FROM EMP E,SALGRADE G
WHERE E.SAL >= G.LOSAL AND E.SAL <= G.HISAL AND GRADE = 4
ORDER BY SAL DESC;
--ANSI JOIN
SELECT EMPNO 사번, ENAME 사원명, SAL 급여, GRADE 등급
FROM EMP E JOIN SALGRADE G
ON E.SAL >= G.LOSAL AND E.SAL <= G.HISAL AND GRADE = 4
ORDER BY SAL DESC;

5. 부서테이블, 사원테이블, 급여등급테이블에서 사번, 사원명, 부서명, 급여, 등급을 검색하시오.
  단, 등급은 급여가 하한값과 상한값 범위에 포함되며 등급을 기준으로 내림차순 정렬할 것.
--ORACLE JOIN
SELECT EMPNO 사번,ENAME 사원명,DNAME 부서명,SAL 급여,GRADE 등급
FROM EMP E,DEPT D,SALGRADE G
WHERE E.DEPTNO = D.DEPTNO AND E.SAL >= G.LOSAL AND E.SAL <= G.HISAL
ORDER BY GRADE DESC;
--ANSI JOIN
SELECT EMPNO 사번,ENAME 사원명,DNAME 부서명,SAL 급여,GRADE 등급
FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
JOIN SALGRADE G
ON E.SAL >= G.LOSAL AND E.SAL <= G.HISAL
ORDER BY GRADE DESC;

6. 사원테이블에서 사원명과 해당 사원의 관리자명을 검색하시오.
--ORACLE JOIN
SELECT E.ENAME 사원명, M.ENAME 관리자명
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO;
--ANSI JOIN
SELECT E.ENAME 사원명, M.ENAME 관리자명
FROM EMP E JOIN EMP M
ON E.MGR=M.EMPNO;
7. 사원테이블에서 사원명, 해당 사원의 관리자명, 해당 사원의 관리자의 관리자명을 검색하시오.
--ORACLE JOIN
SELECT E.ENAME 사원명, M1.ENAME 관리자명, M2.ENAME 관리자의관리자명
FROM EMP E,EMP M1,EMP M2
WHERE E.MGR=M1.EMPNO AND M1.MGR=M2.EMPNO;
--ANSI JOIN
SELECT E.ENAME 사원명, M1.ENAME 관리자명, M2.ENAME 관리자의관리자명
FROM EMP E JOIN EMP M1
ON E.MGR=M1.EMPNO 
JOIN EMP M2
ON M1.MGR=M2.EMPNO;
8. 7번 결과에서 상위 관리자가 없는 모든 사원의 이름도 사원명에 출력되도록 수정하시오.
--ORACLE JOIN
SELECT E.ENAME 사원명, M1.ENAME 관리자명, M2.ENAME 관리자의관리자명
FROM EMP E,EMP M1,EMP M2
WHERE E.MGR=M1.EMPNO(+) AND M1.MGR=M2.EMPNO(+);
--ANSI JOIN
SELECT E.ENAME 사원명, M1.ENAME 관리자명, M2.ENAME 관리자의관리자명
FROM EMP E LEFT OUTER JOIN EMP M1
ON E.MGR=M1.EMPNO 
LEFT OUTER JOIN EMP M2
ON M1.MGR=M2.EMPNO;